# Generated by Django 4.2 on 2023-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=' ^}              ')),
                ('task', models.TextField(verbose_name=' ^~     ^a        ')),
            ],
            options={
                'verbose_name': '  ^w       ^g  ',
                'verbose_name_plural': ' ^w       ^g  ',
            },
        ),
    ]
